{
 "title": "Repositories",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "org", "label": "Organisation", "query": "label_values(prow:job, org)" },
   {
    "name": "repo",
    "query": "label_values(prow:job{org=\"$org\"}, repo)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (repo) (prow:job{org=\"$org\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{repo=~\"$repo\"}) > 60"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (repo) (prow:job{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (repo) (prow:job:pending{org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{org=\"$org\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Repository",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Repository",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{org=\"$org\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage for $repo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "repo",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}